### PR TITLE
Fix theme links in v6 upgrade guide

### PR DESCRIPTION
**Pull request by jnoordsij**

### CODE REVIEW

**Comment by pxpm** [comment]
Thank you @jnoordsij 🙏

**Comment by tabacitu** [comment]
@jnoordsij have you tried the upgrade guide on any real projects? How did the upgrade go?

**Comment by jnoordsij** [comment]
@tabacitu yes! I've managed to follow the upgrade guide without really that much trouble. Decided to stick with migrating to the tabler theme and it works pretty well; still figuring out wether or not I'll try to migrate some of my old manual UI changes or stick with the new default, as I think it looks pretty neat as is.

No real issues either, apart from not being able to fully test file-manager related things yet (https://github.com/Laravel-Backpack/FileManager/issues/28).

Migrating to tabler also went quite ok, though updating some blade templates was a bit tricky. In the end I went with checking some examples in the Tabler docs and the Backpack demo, with which I got things working. Might be helpful to point people in that direction somewhere in the upgrade guide.

**Comment by tabacitu** [comment]
Awesome, glad to hear that @jnoordsij 🙏 The Tabler theme will become even prettier, I promise. It needs another combing through. 

Good idea with the theme links for copy-pasting HTML. Done - https://github.com/Laravel-Backpack/docs/commit/f9ccc3cc7e1ce1be7259d2e643975e22501ddb31

**Pull request merged**
