### PR TITLE
update add-ons-community.md

### PR DESCRIPTION
**Pull request by laraviet**
Add new add-on: laraviet/backpack2fa
- Apply Google Authenticator to Laravel Backpack project

### CODE REVIEW

**Comment by tabacitu** [comment]
Hi @laraviet ,

Great job creating a package for this! I was wondering if we should create a package like this - not only Google Auth but maybe others too - that way admins don't have to remember a password at all.

I'll test it and merge this PR so people could reach your project. I'll also mention it in the newsletter and promote it through our other channels - I'm sure a lot of people will be thankful to you.

Cheers!

**Comment by laraviet** [comment]
Hi @tabacitu ,

Please test my package. And if you have any feedback, please let me know.

Yes, I will try to investigate and public other package for other 2FA mechanism too.
I hope this package will be helpful for people around. 

Thank you very much.

**Comment by karandatwani92** [comment]
Unmaintained third-party package.
Feel free to reopen if compatible with the newer backpack.

**Comment by karandatwani92** [comment]
Hello @laraviet 
Thanks for your backpack package contribution. We value the time, effort & interest you took in creating a 3rd party Backpack package. We're grateful that you created it, but we can't include it on our website since it isn't maintained.

Sorry, I sounded rude and very formal in my previous comment. We appreciate and always love the community's efforts, making the backpack better than ever. Please Feel free to reopen if this could become compatible with the newer backpack versions.

Cheers🍻🙋‍♂️

**Pull request closed without merging**
