### PR TITLE
Missing one of default actions

### PR DESCRIPTION
**Pull request by realtebo**
added `save_and_preview` to save actions

Same fix should be done in 4.2-dev doc

### CODE REVIEW

**Review by olipayne — APPROVED** [review]

**Comment by olipayne** [comment]
Was about to do this myself, definitely missing!

**Review by olipayne — CHANGES_REQUESTED** [review]
PR should also replace `three` with `four` in the sentence above the list.

**Comment by realtebo** [comment]
Too late to merge. please, close but apply modifications to right branches

**Comment by tabacitu** [comment]
Done, and fixed in 5.x docs too - https://github.com/Laravel-Backpack/docs/commit/fb81335be75a75467ef219ed187f65926c96f7c2

Thanks guys!

**Pull request merged**
