### PR TITLE
Add a reference to setFromDb()

### PR DESCRIPTION
**Pull request by peterhauke**
There does not appear to be any reference to this function in the documentation, however it appears in the setupListOperation() and setupCreateOperation() when creating a CrudController, so I added a description (adapted from setFromDb() in AutoSet.php)

### CODE REVIEW

**Comment by karandatwani92** [comment]
Hey, @tabacitu `setFromDb()` is missing in the CRUD **API list**.

Please review and merge.

Thanks @peterhauke

**Comment by tabacitu** [comment]
Thanks for the note @peterhauke !

Actually @karandatwani92 we don't want people using `setFromDb()` - it's deprecated. So instead, let's remove any mentions of it from the docs, please 🙏

Why? Because `setFromDb()` isn't good-enough in the first place. It doesn't properly guess column&field types. And because of a way it was constructed, we can never _ever_ make updates to it. Any updates we do make... are a breaking change to everybody who's using it. That's why we've deprecated it.

PS. I don't know if it already has a `@deprecated` note on the docblock, in the code. If it does not, please do that too @karandatwani92

**Comment by peterhauke** [comment]
I had a look at `setFromDb()` in [autoset.php](https://github.com/Laravel-Backpack/CRUD/blob/4cd8e5d909c77a4d7ce2bfbc7eac46490589ad20/src/app/Library/CrudPanel/Traits/AutoSet.php#L13) and there does not appear to be a deprecated note there.

I had a look at `setupListOperation()` in [crud-controller.stub](https://github.com/Laravel-Backpack/Generators/blob/08a61a0b11b7c657189ffa6bcd45d0b9c28450ef/src/Console/stubs/crud-controller.stub#L42) and there is no mention of it being deprecated there either. 

`setFromDb()` is currently being included in the code when a new crud controller is created.

Sorry for asking, but is there another function to use instead of `setFromDb()` ?

**Comment by karandatwani92** [comment]
Yes, Not appropriate to `@deprecate` as it's in [crud-controller.stub](https://github.com/Laravel-Backpack/Generators/blob/08a61a0b11b7c657189ffa6bcd45d0b9c28450ef/src/Console/stubs/crud-controller.stub#L42) .

 @tabacitu please give directions.

**Comment by promatik** [comment]
@karandatwani92 it's true the `setFromDb` is in the stubs, it should be removed from there, anyway, in the between we can keep it as an example, but developers will be warned that it is deprecated.
I'll close this one, let's move conversation here; https://github.com/Laravel-Backpack/CRUD/pull/5419

**Pull request closed without merging**
