### PR TITLE
Spelling and capitalisations

### PR DESCRIPTION
**Pull request by olipayne**

### CODE REVIEW

**Comment by tabacitu** [comment]
Thank you @olipayne , must have been so annoying!

**Comment by tabacitu** [comment]
Keep 'em coming. What do you think of v5 so far, encountered any big problems?

**Comment by olipayne** [comment]
Saw one and then thought I'd go through it all ;)

I missed the auto v5 subscription by a few days, so I'll let the dust settle and then get for a Pro license!

Only niggle I have so far is in PermissionManager's latest release, you could add support for v4+v5 in one go, I'll submit a PR for that soon.

**Comment by tabacitu** [comment]
> I missed the auto v5 subscription by a few days, so I'll let the dust settle and then get for a Pro license!

Haha it was bound to happen to someone 😀 Gave you access for a year - it's the least we can do for the help.

Cheers!

**Pull request merged**
