### PR TITLE
Fix minor typos, etc.

### PR DESCRIPTION
**Pull request by peterhauke**
I think the brackets were in the wrong place. Or possibly, brackets are not really necessary in this context.

"plain old" is not hyphenated.

### CODE REVIEW

**Comment by peterhauke** [comment]
On line 94, I did not really understand what "Or that you plan to use it for both users & admins." means and how exactly it connects with the previous sentence. So I did not make any changes to that sentence.

**Comment by pxpm** [comment]
Thanks @peterhauke 

I will refrain from merging this one right now because @tabacitu is going to work on this page soon as per https://github.com/Laravel-Backpack/docs/issues/468

For example the `error views` text, we no longer publish error views anymore, so we should remove that, and add instructions on how they work and how they can be customized. 

Thanks 🙏

**Comment by tabacitu** [comment]
Yup, on it! Hopefully later today 🤞

**Comment by peterhauke** [comment]
Thanks @tabacitu , @pxpm 

If you want to assign me a page to look at, then please do so. I quite often have time to read through and correct one page like this a day.

Normally, I am just looking:
- for mistakes;
- to eliminate inconsistencies; and
- to clarify ambiguous text.
 
I try not to change the writing style too much.

**Comment by tabacitu** [comment]
That would be very helpful, yes, thank you. I'll take you up on it 😉 Right now what this page needs... is for us to change to logic of it first. There are things here that were true in v5 but no longer true in v6.

**Pull request closed without merging**
